version: "3.8"
services:
  redis:
    image: redis
    command: redis-server --requirepass zaQ@1234
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

networks:
  devnet:

volumes:
  redis-data:
